name: ci

on: [workflow_dispatch, push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run linter
        run: yarn lint
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [lint-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: eas build --platform all --non-interactive
