name: Production build when pushing to main

on:
  push:
    branches:
      - main

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run linter
        run: yarn lint

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        if: ${{ github.ref == 'refs/heads/main' }}
        run: eas build --platform all --profile production --non-interactive --clear-cache
